output tg_arns {
	value = {
		for name in keys(aws_lb_target_group.tg):
		name => aws_lb_target_group.tg[name].arn
	}
}

output dns{
	description = "DNS name for the NLB"
  value = length(var.dns) == 0 ? aws_lb.nlb.dns_name : var.dns.name
}
output lb_dns {
	description = "DNS name for the NLB generated by AWS"
  value = aws_lb.nlb.dns_name
}
output lb_zone {
  description = "Hosted zone of the NLB"
  value = aws_lb.nlb.zone_id
}
